import Head from 'next/head';
import {Container, VStack} from '@chakra-ui/react';
import {Cards, Header, Filters} from '@/components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Movie Goers</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Header/>
      <Container maxW="4xl" mt={4}>
        <VStack spacing={4} alignItems="left">
          <Filters />
          <Cards/>
        </VStack>
      </Container>
    </>
  )
}
