import Head from 'next/head';
import {Header, Movie} from '@/components';

export default function MoviePage() {
  return (
    <>
      <Head>
        <title>Movie Goers</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Header />
      <Movie />
    </>
  );
}
